model:
  model_name: "CustomerComplaintsModel"

security:
  api_key: "mysecretkey"

data:
  data_path: 'data/complaints_processed.csv'
  log_path: 'data/logged_data.csv'

monitoring:
  data_drift:
    numerical_features: ["input_length", "word_count", "credit", "banking", "debt", "loan"]
    categorical_features: ["product"]