model:
  model_name: "LogisticRegressionModel"

security:
  hashed_token: "2afe16a6d630d94cd07c68d5e35568655bf5f60bef29c4f1321fc857816afec9"

data:
  data_path: 'data/complaints_processed.csv'
  log_path: 'data/logged_data.csv'

monitoring:
  data_drift:
    numerical_features: ["input_length", "word_count", "credit", "banking", "debt", "loan"]
    categorical_features: ["product"]